'use client';
import { useState } from 'react';
import styles from '../demos.module.css';
const examples = [
  { label: 'First attempt', answer: 'I led a transformation across the team. We improved our processes, worked closely with stakeholders and delivered much better results. It was a challenging period, but I’m proud of what we achieved.', feedback: 'The answer names an achievement, but the listener can’t yet see the decision you made or the part you played.', next: 'Choose one decision. What was the constraint, what did you change, and what evidence told you it worked?' },
  { label: 'More specific', answer: 'Our fictional team was treating every vacancy as equally urgent. I asked the leadership group to agree on three business outcomes for the quarter, then used those to prioritise the hiring plan. We stopped spreading the team across every request. I reviewed progress each week with the team leads and adjusted when a critical role stalled.', feedback: 'The listener can now follow a concrete decision, the trade-off behind it and how you kept track of the work.', next: 'Add a result you can support. What changed for the business, and what would you do differently next time?' },
];
export default function InterviewPreview() {
  const [selected, setSelected] = useState(0);
  return <section className={styles.coach}><p>Opportunity discovery & candidate fit</p><h1>Find the roles<br/>you’re missing.</h1><p className={styles.coachIntro}>Radar combines market signals with candidate context to uncover overlooked roles, identify the strongest fit, and curate the journey from first approach to interview.</p><p className={styles.coachNote}>Try one part of that journey below: preparing for the conversation.</p><div className={styles.coachPanel}><span>INTERVIEW COACHING · SCRIPTED PREVIEW</span><h2>“Tell me about a time you changed how a team worked. What did you personally decide?”</h2><div className={styles.choices} aria-label="Choose a sample answer">{examples.map((example, i) => <button key={example.label} aria-pressed={selected === i} onClick={() => setSelected(i)}>{example.label}</button>)}</div><div aria-live="polite"><blockquote className={styles.answer}>{examples[selected].answer}</blockquote><div className={styles.feedback}><section><h3>What the coach notices</h3><p>{examples[selected].feedback}</p></section><section><h3>A useful follow-up</h3><p>{examples[selected].next}</p></section></div></div></div><p className={styles.coachNote}>This is a scripted example, not a live assessment of you. The working voice beta includes role-specific practice, saved transcripts, private notes and feedback; access is currently by invitation. This public preview makes no model calls and uses no candidate records.</p></section>;
}
