import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

test("first-visit menu opens explicitly, resets on dismissal, and stays familiar across routes", async ({ page }) => {
  await page.goto("/building");
  const control = page.locator(".sphere-home");
  const island = page.locator(".nav-island");
  await expect(control).toHaveAttribute("aria-label", "Open navigation");
  await expect(page.locator(".menu-lines > span")).toHaveCount(2);
  await expect(page.locator(".sphere-stage")).toHaveCSS("opacity", "0");
  // Hovering while aiming at the first menu must not change what a click does.
  await control.hover();
  await page.waitForTimeout(250);
  await expect(control).toHaveAttribute("aria-expanded", "false");
  await control.click();
  await expect(control).toHaveAttribute("aria-expanded", "true");
  await expect(page.locator(".sphere-stage")).toHaveCSS("opacity", "1");
  await expect(page.locator(".orbit-portal")).toHaveCount(0);
  expect(await page.evaluate(() => sessionStorage.getItem("tg-orbit-discovered"))).toBeNull();
  await page.keyboard.press("Escape");
  await expect(island).toHaveAttribute("data-moon", "false");
  await expect(page.locator(".menu-lines > span").first()).toHaveCSS("opacity", "1");
  await control.click();
  await page.getByRole("navigation", { name: "Primary navigation" }).getByRole("link", { name: "About", exact: true }).click();
  await expect(page).toHaveURL(/\/about$/);
  await expect(island).toHaveAttribute("data-moon", "false");
  await page.reload();
  await expect(island).toHaveAttribute("data-moon", "false");
});

test("touch discovery keeps the Moon across routes and reloads but a fresh visit starts with lines", async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 430, height: 932 }, isMobile: true, hasTouch: true, reducedMotion: "reduce" });
  const page = await context.newPage();
  await page.goto("/building");
  const control = page.locator(".sphere-home");
  const island = page.locator(".nav-island");
  await control.tap();
  await expect(control).toHaveAttribute("aria-expanded", "true");
  await expect(page.locator(".orbit-portal")).toHaveCount(0);
  await page.locator("body").tap({ position: { x: 25, y: 500 } });
  await expect(island).toHaveAttribute("data-moon", "false");
  await control.tap();
  await control.tap();
  await expect(page.locator(".orbit-portal .orbit-poster")).toBeVisible();
  await expect.poll(() => page.evaluate(() => sessionStorage.getItem("tg-orbit-discovered"))).toBe("1");
  await page.keyboard.press("Escape");
  await expect(page.locator(".orbit-portal")).toHaveCount(0);
  await page.locator("body").tap({ position: { x: 25, y: 500 } });
  await expect(island).toHaveAttribute("data-expanded", "false");
  await expect(island).toHaveAttribute("data-moon", "true");
  await expect(page.locator(".sphere-stage")).toHaveCSS("opacity", "1");
  await control.tap();
  await expect(page.locator(".orbit-portal")).toHaveCount(0);
  await page.getByRole("navigation", { name: "Primary navigation" }).getByRole("link", { name: "About", exact: true }).tap();
  await expect(page).toHaveURL(/\/about$/);
  await expect(island).toHaveAttribute("data-moon", "true");
  await page.reload();
  await expect(island).toHaveAttribute("data-moon", "true");
  await expect(page.locator("html")).toHaveAttribute("data-orbit-discovered", "true");
  await expect(page.locator(".sphere-stage")).toHaveCSS("opacity", "1");
  await expect(page.locator(".menu-lines > span").first()).toHaveCSS("opacity", "0");
  await context.close();
  const fresh = await browser.newContext();
  const newPage = await fresh.newPage();
  await newPage.goto("/building");
  await expect(newPage.locator(".nav-island")).toHaveAttribute("data-moon", "false");
  await fresh.close();
});

test("keyboard discovery works without session storage and navigation remains accessible", async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(window, "sessionStorage", { get() { throw new DOMException("Blocked", "SecurityError"); } });
  });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/building");
  const control = page.locator(".sphere-home");
  await control.focus();
  await expect(control).toHaveAttribute("aria-expanded", "false");
  await page.keyboard.press("Enter");
  await expect(control).toHaveAttribute("aria-expanded", "true");
  await expect(page.locator(".sphere-stage")).toHaveCSS("opacity", "1");
  const audit = await new AxeBuilder({ page }).include(".site-header").analyze();
  expect(audit.violations).toEqual([]);
  await page.keyboard.press("Enter");
  await expect(page.locator(".orbit-portal")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.locator(".orbit-portal")).toHaveCount(0);
  await page.keyboard.press("Escape");
  await expect(page.locator(".nav-island")).toHaveAttribute("data-expanded", "false");
  await expect(page.locator(".nav-island")).toHaveAttribute("data-moon", "true");
  await control.hover();
  await expect(control).toHaveAttribute("aria-expanded", "true");
  await page.getByRole("navigation", { name: "Primary navigation" }).getByRole("link", { name: "About", exact: true }).click();
  await expect(page).toHaveURL(/\/about$/);
  await expect(page.locator(".nav-island")).toHaveAttribute("data-moon", "true");
});
